#!/usr/bin/env python3
"""AOT-translate a Thumb window of a GBA ROM into C for the ESP32 port.

Not a semantic recompiler: every instruction is emitted as a call to the
interpreter's OWN static handler with the opcode as a compile-time constant.
GCC inlines the handler and constant-folds the decode, which removes the
table dispatch, operand decode and pipeline shuffle (the bulk of thumb cpi)
while keeping semantics and cycle charges identical by construction.

Blocks run leader-to-leader (leaders: window entry, branch targets inside
the window, instructions after bl). After every instruction the emitted
code re-checks that control actually fell through and that no scheduled
event is due; any deviation returns to the interpreter, whose next
iteration re-enters the table -- translated and interpreted code interleave
freely at instruction granularity.

Usage:
  xlate.py rom.gba 0x6400 0x6c40 BPEJ > aot_gen_bpej.inc

The output is #included at the end of src/gba.cpp (it calls static
handlers), and registers itself via espgba_aot_register().
"""
import sys

import capstone


def handler_symbol(op):
    """Map a 16-bit thumb opcode to the interpreter's handler symbol.

    The dispatch is thumbInsnTable[opcode>>6], 1024 entries named
    thumbHH_SS where HH is the top byte class and SS the sub-index, as
    laid out in gba.cpp. Reconstruct the name from the table's layout:
    entry i corresponds to opcode class (i>>2) in hex and sub (i&3)...
    -- the actual table is not uniform, so we parse it from gba.cpp.
    """
    raise RuntimeError("filled in by load_table")


def load_table(gba_cpp):
    """Parse thumbInsnTable[1024] initializer from gba.cpp -> symbol list."""
    src = open(gba_cpp).read()
    start = src.index("static insnfunc_t thumbInsnTable[1024]")
    start = src.index("{", start)
    end = src.index("};", start)
    body = src[start + 1:end]
    lines = [ln.split("//")[0] for ln in body.splitlines()
             if not ln.strip().startswith("#")]
    syms = []
    for tok in " ".join(lines).split(","):
        tok = tok.strip()
        if tok:
            syms.append(tok)
    if len(syms) != 1024:
        raise SystemExit(f"parsed {len(syms)} entries, want 1024")
    return syms


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--hot=")]
    hot = []
    for a in sys.argv[1:]:
        if a.startswith("--hot="):
            hot = [int(x, 0) for x in a[6:].split(",") if x]
    rom_path, w0, w1, tag = (args[0], int(args[1], 0),
                             int(args[2], 0), args[3])
    rom = open(rom_path, "rb").read()
    table = load_table(sys.path[0] + "/../../components/gba/gba.cpp")

    md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_THUMB)
    md.skipdata = True
    base = 0x08000000

    # First pass: decode every halfword position that is plausibly code and
    # collect leaders. Literal pools decode as junk; they are never entered
    # (no leader points at them) and never emitted as fallthrough because
    # the preceding instruction is an unconditional exit (b/bx/pop-pc/bl).
    insns = {}
    for insn in md.disasm(rom[w0:w1], base + w0):
        insns[insn.address] = insn

    leaders = set()
    leaders.add(base + w0)
    for a, insn in insns.items():
        m = insn.mnemonic
        if m == "bl":
            leaders.add(a + 4)  # return target
        if m.startswith("b") and m not in ("bl", "blx", "bx", "bic", "bics"):
            # branch (conditional or not): target inside window is a leader,
            # and so is the fallthrough of a conditional
            try:
                tgt = int(insn.op_str.lstrip("#"), 0)
                if base + w0 <= tgt < base + w1:
                    leaders.add(tgt)
            except ValueError:
                pass
    leaders = sorted(x for x in leaders if x in insns)

    out = sys.stdout
    out.write(f"/* AOT-generated from {tag}: window "
              f"0x{base+w0:08x}..0x{base+w1:08x}.\n"
              f" * GENERATED by tools/aot/xlate.py -- do not edit. */\n\n")

    emitted_blocks = []
    for li, leader in enumerate(leaders):
        limit = leaders[li + 1] if li + 1 < len(leaders) else base + w1
        pc = leader
        body = []
        while pc < limit and pc in insns:
            insn = insns[pc]
            op = int.from_bytes(rom[pc - base:pc - base + 2], "little")
            if insn.size != 2 and insn.mnemonic != "bl":
                break  # 32-bit non-bl (data / unexpected): stop emitting
            if insn.mnemonic in ("svc", "swi", "udf", "bkpt") or \
                    insn.mnemonic.startswith("."):
                break  # never emit; the interpreter takes over here
            sym = table[op >> 6]
            nxt = pc + insn.size
            body.append(f"   /* {pc:08x}: {insn.mnemonic} {insn.op_str} */")
            if insn.mnemonic == "bl":
                # bl is two halfwords, two handler calls in this core
                op2 = int.from_bytes(rom[pc - base + 2:pc - base + 4],
                                     "little")
                body.append(f"   AOT_STEP(0x{pc:08x}u, {table[op >> 6]}, "
                            f"0x{op:04x}u, 0x{pc + 2:08x}u);")
                body.append(f"   AOT_STEP(0x{pc + 2:08x}u, "
                            f"{table[op2 >> 6]}, 0x{op2:04x}u, "
                            f"0x{nxt:08x}u);")
            else:
                body.append(f"   AOT_STEP(0x{pc:08x}u, {sym}, 0x{op:04x}u, "
                            f"0x{nxt:08x}u);")
            ender = insn.mnemonic in ("b", "bx", "bl") or \
                (insn.mnemonic == "pop" and "pc" in insn.op_str)
            pc = nxt
            if ender:
                break
        if not body:
            continue
        if hot and not any(h < pc and leader < h + 0x40 for h in hot):
            continue  # cold block: leave it to the interpreter
        fn = f"aot_{tag.lower()}_{leader:08x}"
        emitted_blocks.append((leader, fn))
        out.write(f"static void {fn}(void)\n{{\n")
        out.write("\n".join(body))
        out.write("\n   AOT_EXIT();\n}\n\n")

    # registration table
    out.write(f"static const espgba_aot_entry espgba_aot_{tag.lower()}[] "
              "= {\n")
    for addr, fn in emitted_blocks:
        out.write(f"   {{0x{addr:08x}u, {fn}}},\n")
    out.write("   {0u, 0},  /* sentinel so the array is never empty */\n")
    out.write("};\n\n")

    # The console's flash copy carries the m4a downrate patch: SoundMode
    # literals 0x0094C500 become 0x0090C500|(idx<<16) during the copy.
    # Hash what the DEVICE will read, not the pristine file.
    FREQ_IDX = 2
    win = bytearray(rom[w0:w1])
    for o in range(0, len(win) - 3, 4):
        if int.from_bytes(win[o:o+4], "little") == 0x0094C500:
            win[o:o+4] = (0x0090C500 | (FREQ_IDX << 16)).to_bytes(4, "little")
    h = 0xcbf29ce484222325
    for byt in win:
        h = ((h ^ byt) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    out.write(f"/* window FNV-1a-64 for arming eligibility */\n"
              f"#define ESPGBA_AOT_{tag}_BASE 0x{base+w0:08x}u\n"
              f"#define ESPGBA_AOT_{tag}_END  0x{base+w1:08x}u\n"
              f"#define ESPGBA_AOT_{tag}_HASH 0x{h:016x}ull\n"
              f"#define ESPGBA_AOT_{tag}_N    "
              f"{len(emitted_blocks)}\n")
    print(f"/* {len(emitted_blocks)} blocks, "
          f"{len(leaders)} leaders */", file=sys.stderr)


if __name__ == "__main__":
    main()
